# Items that apply to ALL profiles, all (eureka) clients get eureka url/defaultzone from this yml file
---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://${cloud_host}:8761/eureka/, http://${cloud_host}:8762/eureka/
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
